[tool.black]
# exclude filters out files found by Black itself during discovery
exclude = '''
(
  .*/antlr_parser/.*\.py
  | .*/proto_gen/.*\.py
)
'''
# pre-commit passes files into Black, rather than letting it discover files
# force-exclude can be used to filter out these files from formatting
force-exclude = '''
(
  .*/antlr_parser/.*\.py
  | .*/proto_gen/.*\.py
)
'''

[tool.pytest.ini_options]
pythonpath = ["proto_gen"]